export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const CHECK_TODO_ITEM = 'CHECK_TODO_ITEM';
export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';

export default {
  ADD_TODO_ITEM,
  CHECK_TODO_ITEM,
  EDIT_TODO_ITEM,
  DELETE_TODO_ITEM,
};
